### ISSUE TITLE
xDnsRecord: `Get-DnsServerResourceRecord` is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Sawal72** [dsccommunity/xDnsServer#98]
#### Details of the scenario you tried and the problem that is occurring
import-module dnsserver is missing in module xDnsRecord

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by rchristman89** [comment]
@Sawal72  is this when the resource is being applied by the LCM?

**Comment by Sudman1** [comment]
This happened to me when using the latest versions of pester and sampler in the required modules. Setting them to 4.10.1 and 0.105.6 respectively, as in jcuzzi's MX record PR fixed this for me.

**Comment by johlju** [comment]
The module xDnsServer should normally load automatically when using a cmdlet from the module, but the resource throughout the repo could use [`Assert-Module`](https://github.com/dsccommunity/DscResource.Common#assert-module) with the parameter `ImportModule` to really make sure the module is available.

**Comment by Sudman1** [comment]
The problem is not actually access to xDnsServer. Not really anyway. It seems to be due to the way Pester 5 treats the InModuleScope cmdlet vs how it is handled in Pester 4.

**Comment by johlju** [comment]
I don't think Pester was the root cause. 🤔 When LCM tried to implement a configuration and are resource is run the **DnsServer** module should be available and most (all?) resource expect it do be automatically imported when using a cmdlet that is part of the module. It looks to me that this did not happen. To handle this the resources should import **DnsServer** into it's module scope, for example by running `Assert-Module -Name 'ModuleName' -ImportModule`. In the case of Pester then when using `InModuleScope` to run tests the module **DnsServer** is present in the resources module scope an `Mock`s should also work. 🤔

**Comment by johlju** [comment]
This resource is now deprecated and will be removed in the near future. New resources covers the functionality.
